### ISSUE TITLE
smoke-test/test.sh fails if path has spaces in name

### ISSUE THREAD

**Issue by bmagyar** [vvv-school/vvv18#12]
FYI @vvv-school/vvv18-students 

If your `test.sh` fails on line 41 with "too many arguments" error, check the result of 
`pwd`.

Example: `/home/me/vvv18 install folder/awesome_tutorial` will fail to run the smoke-test.

@pattacini maybe this needs to be propagated to all smoke-test scripts for next year?

**Comment by pattacini** [comment]
Thanks for reporting 👍

**Comment by pattacini** [comment]
@vvv-school/vvv17-teachers and @vvv-school/vvv18-teachers please update the `smoke-test/test.sh` script in your tutorials/assignments/solutions repos by applying the following patch: https://github.com/vvv-school/assignment_git/commit/24da10b178dbe8a161a955fd29ddadcd1176699d

I've already dealt with my repos.

**Comment by vtikha** [comment]
Done for all vision repos

**Comment by pattacini** [comment]
I think we're mostly done.
