### ISSUE TITLE
Debugging hints

### ISSUE THREAD

**Issue by Nicogene** [vvv-school/vvv18#13]
Dear @vvv-school/vvv18-students, I report here some debugging tips that can be useful for the next assignments but also in general for the future if you will work in a Linux environment 😉 

- `$ ps aux | grep <exec_name>` : `ps aux` will print on the terminal the list of processes running on your pc, `grep <exec_name>` will filter them showing only the one containing the <exec_name> in the name

- `$ killall <exec_name>`: send a `SIGINT` to the `<exec_name>` process. If doesn't work try to kill it with  `killall -9 <exec_name>`. ⚠️ Pay attention that in this case a `SIGKILL` signal is sent and if the executable opened some ports they could still be there. A `yarp clean --timeout 2.0` should solve this problem 😉 

- `$ kill <proc_number>`: the same things about `killall` but in this case you have to give it the process identifier a.k.a PID.

- `$ lsof -ti tcp:<port_number>`: will give you the PID of the process that is holding the socket on port <port_number>.

Happy debugging 🐞

**Comment by marco-monforte** [comment]
I would add that if `$ kill <proc_number>` does not work, you can try with `$ kill -s 9 <process>`, which is more "brutal". For instance, the first instruction often does not work with the iCub simulator (iCub_SIM); the second will do the job.

Moreover, another useful tip I think is that you can press Ctrl+R to do inverse research of previous commands. Try it to better understand :)
