### ISSUE TITLE
Modifications to the environment necessary for Dynamics hands-on

### ISSUE THREAD

**Issue by traversaro** [vvv-school/vvv18#25]
Hi @vvv-school/vvv18-students ! 

I hope you are enjoying @DanielePucci's lectures.  

To get ready for the hands on session in the afternoon, there is a small patch you have to apply to the `~/.bashrc-dev` file in your virtual machine environment. After the line `source /usr/share/gazebo/setup.sh` you have to add the line 
~~~sh
export GAZEBO_RESOURCE_PATH=${GAZEBO_RESOURCE_PATH}:${ROBOT_INSTALL}/share/gazebo/worlds
~~~
This line is necessary to make sure that the [Gazebo simulator](http://gazebosim.org/) finds the [world files](http://gazebosim.org/tutorials?tut=build_world&cat=build_world) that we installed for the dynamics tutorials and assignments. For more info about the `GAZEBO_RESOURCE_PATH` env variable, please check the [Gazebo documentation](http://gazebosim.org/tutorials?tut=components).

Furthermore, we will use the [`YARP_ROBOT_NAME`](http://www.yarp.it/yarp_data_dirs.html) environmental variable to write controllers that are able to run on different robots without code modifications. 
We set this variable in yarpmanager configuration files that we give you, but if you want to run the controllers from the command line, you may want to set this environmental variable directly in your `~/.bashrc-dev` file, for example by adding these two lines to the end of the file:
~~~sh
# Robot-specific configuration
export YARP_ROBOT_NAME=iCubGazeboV2_5
~~~
Note that you want to run your code on one of the two robots present in the school, you have to set the `YARP_ROBOT_NAME` environment variable to `iCubGenova01` (black robot) or `iCubGenova02` (purple robot).

If you have any problem with this, please ask to me (@traversaro) or @diegoferigo , thanks! 

---

Edit (by Diego):

Add also this alias to the same `bashrc-dev` file:

```
alias matlab='LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 matlab'
```

**Comment by marco-monforte** [comment]
@traversaro @diegoferigo I don't have the `~/.bashrc-env` file in my Home folder of the VM. Is it ok to create a new one and copy the lines or is it something I'm missing?

**Comment by traversaro** [comment]
Thanks @marco-monforte , I meant `~/.bashrc-dev`, I modified the original post.
