### ISSUE TITLE
Bug fix in tutorial_impedance-control

### ISSUE THREAD

**Issue by prashanthr05** [vvv-school/vvv18#28]
The tutorial_impedance_control module name seems to have a bug when called through the yarpmanager. To fix this open the  
`tutorial_impedance-control-{your_name}/app/scripts/tutorial_impedance-control-app.xml` with your favorite text editor and find the tag 
```xml
<name>tutorial_impedance-control</name>
```

and change it to 

```xml
<name>tutorial_impedance_control</name>
```

Save the file, go to the build directory and do a `make install`. Reopen `yarpmanager` and try running the module again. Should work fine!

**Comment by prashanthr05** [comment]
@vvv-school/vvv18-students

**Comment by pattacini** [comment]
Or even better, change the project name from `tutorial_impedance_control` to `tutorial_impedance-control` into the CMakeLists.txt file.
