### ISSUE TITLE
Astro-iCub

### ISSUE THREAD

**Issue by kosenhitatchi** [vvv-school/vvv18#33]
<p align="center">
  <img alt="astro-iCub" src="https://image.ibb.co/ifSo0n/astro_icub.png">
@DanielePucci should we call you now <b>Doctor Tenma</b> ?
</p>

**Comment by kosenhitatchi** [comment]
@vvv-school/vvv18-students @vvv-school/vvv18-teachers

**Comment by DanielePucci** [comment]
The link does not work! 😄

**Comment by kosenhitatchi** [comment]
@DanielePucci : Solved 🚀
