### ISSUE TITLE
Event-driven Assignment #2

### ISSUE THREAD

**Issue by arrenglover** [vvv-school/vvv18#37]
https://classroom.github.com/a/9tTMl6He

**Comment by pattacini** [comment]
@vvv-school/vvv18-students please reply to this post if you're having trouble with accepting this assignment so that we can track down here the current status.

**Comment by PCH313** [comment]
Cannot get the assignment :'(

**Comment by umgnunes** [comment]
Me too

**Comment by osm3000** [comment]
I've a problem as well, but I feel okay, my emotions are fine :-D

**Comment by AbbasSidaoui** [comment]
Cannot get it too

**Comment by DonatiElisa** [comment]
and me

**Comment by ninja777** [comment]
It's stuck at loading for me... :crossed_fingers:

**Comment by njm12** [comment]
me too

**Comment by UgVo** [comment]
Currently : "Optimizing repository and pushing commits to GitHub…"

**Comment by fbottarel** [comment]
Mine actually loaded, but the repo is empty...

**Comment by pattacini** [comment]
Everyone should be ok now, if not just come to me!
