### ISSUE TITLE
Installation of 2 missing packages for the Deep Learning hands-on

### ISSUE THREAD

**Issue by GiuliaP** [vvv-school/vvv18#39]
Hi @vvv-school/vvv18-students !

To get ready for the hands on session of tomorrow's afternoon, you should install on the VM two additional packages that have not been installed beforehand. 

You can do this by doing:

```sh
$ sudo apt install python-pip
$ pip install easydict
```

If you have any problem with this, please ask to me or @Arya07  , thanks!
See you tomorrow!

**Comment by pattacini** [comment]
Hi @GiuliaP 
could you please update our internal installation page?

**Comment by pattacini** [comment]
@GiuliaP I've done it.

**Comment by GiuliaP** [comment]
Thanks @pattacini
