### ISSUE TITLE
Slides from Rich

### ISSUE THREAD

**Issue by lornat75** [vvv-school/vvv18#47]
I have slides from Rich's talk yesterday. He prefers not to make them public, so please come with a USB stick.

**Comment by ChiaraBartolozzi** [comment]
lo, per noi le potresti mettere sullo shared drive?

grazie
C

On 15 Feb 2018, at 10:23, Lorenzo Natale <notifications@github.com<mailto:notifications@github.com>> wrote:


I have slides from Rich's talk yesterday. He prefer not to make them public, so please come with a USB stick.

**Comment by lornat75** [comment]
fatto
