### ISSUE TITLE
DELL laptop charger

### ISSUE THREAD

**Issue by fbottarel** [vvv-school/vvv18#53]
Somebody left a small 45W DELL laptop charger in the conference room of the hotel. Check your bags, you might have forgotten about it!

**Comment by traversaro** [comment]
cc @vvv-school/vvv18-students @vvv-school/vvv18-teachers

**Comment by arrenglover** [comment]
That’s mine thanks.

**Comment by fbottarel** [comment]
I think it was taken to IIT together with the iCub equipment!
