### ISSUE TITLE
USB stick

### ISSUE THREAD

**Issue by fbottarel** [vvv-school/vvv18#55]
Somebody left a black USB stick with KOOTION written over it. Come get it in the conference room!

**Comment by traversaro** [comment]
cc @vvv-school/vvv18-students @vvv-school/vvv18-teachers

**Comment by traversaro** [comment]
@fbottarel Almost none of the students is currently watching this repo (https://github.com/vvv-school/vvv18/watchers, so remember to reference the appropriate group if you want to send a communication).

**Comment by pattacini** [comment]
@fbottarel that USB stick might be the one we made circulate to share VM and slides. If so, it's ours, more specifically Matteo Brunettini lent us. Thus, has it been shipped back to Genoa along with the robots?

**Comment by fbottarel** [comment]
I honestly don't know, I came away right after we packed the equipment...

**Comment by pattacini** [comment]
Our pen drive has been found and brought back to Matteo.
