### ISSUE TITLE
Cannot Setup ICUBcontrib (optional)？

### ISSUE THREAD

**Issue by YANGGANG1971** [vvv-school/vvv18#62]
When trying to set up the[ ICUBcontrib](http://wiki.icub.org/wiki/Linux:Installation_from_sources), the reminders said I need to change CMAKE_INSTALL_PREFIX entry here to the path of your liking, preferably in your home and set up the environment.
But I cannot change the CMAKE_INSTALL_PREFIX entry and it does not work as follows.
![image](https://user-images.githubusercontent.com/55526431/70199878-301c2a80-1756-11ea-83a3-23778d7ca9b8.png)
Also, while setting up the new environment, ICUBcontrib_DIR, CMAKE_PREFIX_PATH, YARP_DATA_DIRS cannot be found in the setting panel as follows.
![image](https://user-images.githubusercontent.com/55526431/70199889-39a59280-1756-11ea-8caf-832126cfdb8e.png)

**Comment by pattacini** [comment]
Let me transfer this issue to Q&A, that is the place devoted to this kind of request.
