### ISSUE TITLE
The following links are invalid

### ISSUE THREAD

**Issue by YANGGANG1971** [vvv-school/vvv18#63]
Check your system: http://wiki.icub.org/iCub/main/dox/html/compile_status.html

**Comment by pattacini** [comment]
Thanks for pointing this out: fixed.
Anyway, all the issues related to our wikis and the procedures to install software should go to [Q&A][1] rather than here. I would keep this GitHub organization only for the concerns relative to the VVV school.

[1]: https://github.com/robotology/QA

**Comment by YANGGANG1971** [comment]
OK. Thank you very much.
