### ISSUE TITLE
How to use Python to control iCub?

### ISSUE THREAD

**Issue by YANGGANG1971** [vvv-school/vvv18#64]
Sorry, I am still unclear to know how to build a bidirectional communication interface between Python and Yarp.
I want to collect the sensory information from iCub using Python. And then, Python will process these data. Finally, the calculated outcome after the Python process will transfer to iCub and control the movement.  
Could you give me more details to learn about it?

**Comment by pattacini** [comment]
@YANGGANG1971 I'm transferring this issue to Q&A, which is the right place where discussing these topics.
